# Causality and Selection Bias

###  The causal if-then question

在實證研究要回答一個因果關係是不容易的一件事，縱使是一個直覺上非常簡單的若不小心也會產生誤導的結果。只能說，想要捕捉真實世界的樣貌並不是件容易的事，所以我們需要學習各種計量方法。

來看一個簡單的例子。

Do hospital make people healthier? 

|       Group | Sample size | Mean Health Status |   sd. |
| ----------: | ----------: | -----------------: | ----: |
|    Hospital |        7774 |               3.21 | 0.014 |
| No Hospital |      90.049 |               3.93 | 0.003 |

怎麼看起來有去醫院看醫生的人，健康狀況反而不如沒有去看醫生的人呢？難道醫療的效果是負的嗎？

其實，不能夠忽略會去醫院的人，本身的健康狀況肯定是比較差的。若我們沒有先控制住 __有去醫院的那群人__，以及 __沒有去醫院的那群人__，本質上的不同的話，我們就可能會做出令人匪夷所思的判斷...

所以我們不應該由敘述統計量的帳面數字，就將其詮釋為因果關係的大小、方向等等。

### Potential Outcome Framework

自1990年代開始，計量經濟學對因果關係的探究，有受到醫學實驗領域的影響，總希望能夠在現實生活中製造出一個很像實驗室真空的環境來捕捉因果關係（這也是實驗經濟學最主要的核心精神，背後比較廣泛的概念稱為Randomized Controlled Trial, RCT）。

受限於RCT的成本較高，有些可能涉及研究倫理道德議題，因此若是要用資料(Data)來下手的話，也是會想要設計成彷彿大自然冥冥之中安排好的經歷一樣，我們稱做Natural Experiment。

所有的實驗都有實驗組（treatment group），以及對照組（controlled group）。而實驗前本身就會想要設定兩組樣本的特性是一樣的，也就是俗稱的立足點相同。

但是在Natural Experiment裡面，舉例來說 __上大學對薪資的影響__，同一個樣本，我永遠只能知道有上大學後現在的他，但是我就是看不到 __如果__ 沒有上大學的他，表現又是如何。

__可觀察到的結果永遠只有一個__

以數學表示：

#### Potential Outcome
$$
Potnetial\ outcome =
\begin{cases}
Y_{1i} & if & D_i=1\\
Y_{0i} & if & D_i=0\\
\end{cases}
$$
$D_i = 1$ 表示有接受Treatment.

#### Observed Outcome

i = 1則＝$Y_{1i}$。反之，i = 0則＝$Y_{0i}$。只有一種結果。

$$
Observed\ outcome =
Y_i = Y_{1i}D_i + Y_{0i}(1-D_i)
$$
#### Counterfactual outcome

對於有接受treatment，像是有上大學的小明，沒有上大學的他，是無法觀察到的，我們就稱 __沒有上大學的他__ 為Counterfactual outcome。

### 小結論

由observed outcome簡單化減：$Y_i = Y_{0i}+(\underset{causal\ effect}{\underbrace{Y_{1i}-Y_{0i}}})D_i$

綜合以上，因為potential outcome，我們就是無法兩個都看到。因此在可視得結果(observed outcome)下，學習進階的計量技巧，拆解出我們要的因果關係部分。


### Estimation of Causal Effects

因為我們不可能只在意一個人接受treatment後的改善程度，我們會想要去一般化我們的估計結果，所以自然是詮釋為 __average causal effect__。因此就會有 _Expectation_的期望值概念。

#### Information dismantling

> 現在我們要進行訊息拆解。

$$
\underset{Observed\ diff.\ in\ average\ outcome}{\underbrace{\mathbb{E}(Y_i|D_i=1)-\mathbb{E}(Y_i|D_i = 0)}} = \\
\underset{average\ treatment\ effect\ on\ treatment}{\underbrace{\mathbb{E}(Y_{1i}|D_i=1)-\mathbb{E}(Y_{0i}|D_i = 1)}}\ + 
\underset{selection\ bias}{\underbrace{\mathbb{E}(Y_{0i}|D_i=1)-\mathbb{E}(Y_{0i}|D_i = 0)}}\ 
$$

#### ATT 

> The Average Treatment effect on the Treatment


#### Selection Bias


#### CATE

#### ATE

> 說明一下ATE，比ATT夠更難求到。基於定義就可以知道。他的樣本群要求更大。



### Numerical Example

#### Real situation 

#### Assume the counterfactual outcomes are observable




